name: Update Formula

on:
  repository_dispatch:
    types: [released]

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update formula file
        run: |
          VERSION=$(echo ${{ github.event.client_payload.ref }} | sed -e "s#refs/tags/##g")
          BINARY=${{ github.event.client_payload.binary }}
          FORMULA=${{ github.event.client_payload.formula }}
          ASSET=${{ github.event.client_payload.asset }}
          REPO=${{ github.event.client_payload.repo }}
          URL="https://github.com/${REPO}/releases/download/${VERSION}/${ASSET}"
          cat <<EOF > Formula/${FORMULA}.rb
          class ${{ github.event.client_payload.class }} < Formula
            homepage "https://github.com/${REPO}"
            url "${URL}"
            sha256 "${{ github.event.client_payload.sha256 }}"

            def install
              bin.install "${BINARY}"
            end
          end
          EOF

      - name: Commit version change
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update ${{ github.event.client_payload.formula }} to ${{ github.event.client_payload.ref }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
